version: '3'
services:
  web:
    image: "alphablocks/mask-rcnn"
    ports:
      - 9000:9000
    volumes:
      - .:/project
    environment:
      WEB_ENV: development
  redis:
    image: "redis:alpine"
